/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui;

import javax.swing.JOptionPane;
import os_generator.OS_Generator;

/**
 *
 * @author gabif
 */
public class ClientDataUI extends javax.swing.JFrame {

    /**
     * Creates new form ClientDataUI
     */
    public ClientDataUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titleLabel = new javax.swing.JLabel();
        clienteLabel = new javax.swing.JLabel();
        condutorLabel = new javax.swing.JLabel();
        veiculoLabel = new javax.swing.JLabel();
        placaLabel = new javax.swing.JLabel();
        anoLabel = new javax.swing.JLabel();
        motorLabel = new javax.swing.JLabel();
        clientNameField = new javax.swing.JTextField();
        condutorNameField = new javax.swing.JTextField();
        veiculoField = new javax.swing.JTextField();
        placaField = new javax.swing.JTextField();
        anoField = new javax.swing.JTextField();
        motorField = new javax.swing.JTextField();
        avancarButton = new javax.swing.JButton();
        voltarButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        titleLabel.setText("Informações do Cliente e Veículo");

        clienteLabel.setText("Nome Cliente:*");

        condutorLabel.setText("Nome Condutor:");

        veiculoLabel.setText("Veículo:*");

        placaLabel.setText("Placa:*");

        anoLabel.setText("Ano:*");

        motorLabel.setText("Motor:");

        avancarButton.setText("Avançar");
        avancarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                avancarButtonActionPerformed(evt);
            }
        });

        voltarButton.setText("Voltar");
        voltarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voltarButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(clienteLabel)
                            .addComponent(condutorLabel)
                            .addComponent(veiculoLabel)
                            .addComponent(placaLabel)
                            .addComponent(anoLabel)
                            .addComponent(motorLabel))
                        .addGap(16, 16, 16)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(veiculoField, javax.swing.GroupLayout.DEFAULT_SIZE, 162, Short.MAX_VALUE)
                            .addComponent(condutorNameField, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE)
                            .addComponent(clientNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(motorField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                                    .addComponent(anoField, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(placaField, javax.swing.GroupLayout.Alignment.LEADING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(avancarButton, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(voltarButton, javax.swing.GroupLayout.Alignment.TRAILING)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(150, 150, 150)
                        .addComponent(titleLabel)))
                .addContainerGap(85, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {clientNameField, condutorNameField, veiculoField});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {avancarButton, voltarButton});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {anoLabel, clienteLabel, condutorLabel, motorLabel, placaLabel, veiculoLabel});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(titleLabel)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(clienteLabel)
                    .addComponent(clientNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(condutorLabel)
                    .addComponent(condutorNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(veiculoField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(veiculoLabel))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(placaLabel)
                    .addComponent(placaField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(avancarButton)
                    .addComponent(anoField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(anoLabel))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(voltarButton)
                    .addComponent(motorField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(motorLabel))
                .addContainerGap(50, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void voltarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voltarButtonActionPerformed
        // TODO add your handling code here:
        OS_Generator.clientData.setVisible(false);
        OS_Generator.menu.setVisible(true);
    }//GEN-LAST:event_voltarButtonActionPerformed

    private void avancarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_avancarButtonActionPerformed
        // TODO add your handling code here:

        if (clientNameField.getText().isBlank() || veiculoField.getText().isBlank()
                || placaField.getText().isBlank() || anoField.getText().isBlank()) {
            JOptionPane.showMessageDialog(null,
                    "Warning - Preencha todos os campos obrigatórios marcados com *",
                    "Warning", 0);
        } else {
            salvaDados();
        }


    }//GEN-LAST:event_avancarButtonActionPerformed

    private void salvaDados() {

        try {
            int ano = Integer.parseInt(this.anoField.getText());

            OS_Generator.atualizaCliente(this.clientNameField.getText(),
                    this.condutorNameField.getText(),
                    this.veiculoField.getText(),
                    this.placaField.getText(),
                    ano,
                    this.motorField.getText());
            OS_Generator.clientData.setVisible(false);
            OS_Generator.factory.setVisible(true);
        } catch (NumberFormatException e) {
            System.err.println("Erro - O ano informado é inválido!");
            JOptionPane.showMessageDialog(null, "Erro - O ano informado é inválido", "Warning - Error", 0);
        }// try-catch

    }

    public void resetaCampos() {
        this.clientNameField.setText("");
        this.condutorNameField.setText("");
        this.veiculoField.setText("");
        this.placaField.setText("");
        this.anoField.setText("");
        this.motorField.setText("");
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ClientDataUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new ClientDataUI().setVisible(false);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField anoField;
    private javax.swing.JLabel anoLabel;
    private javax.swing.JButton avancarButton;
    private javax.swing.JTextField clientNameField;
    private javax.swing.JLabel clienteLabel;
    private javax.swing.JLabel condutorLabel;
    private javax.swing.JTextField condutorNameField;
    private javax.swing.JTextField motorField;
    private javax.swing.JLabel motorLabel;
    private javax.swing.JTextField placaField;
    private javax.swing.JLabel placaLabel;
    private javax.swing.JLabel titleLabel;
    private javax.swing.JTextField veiculoField;
    private javax.swing.JLabel veiculoLabel;
    private javax.swing.JButton voltarButton;
    // End of variables declaration//GEN-END:variables
}
