/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui;

import os_generator.OS_Generator;

/**
 *
 * @author gabif
 */
public class FactoryUI extends javax.swing.JFrame {

    /**
     * Creates new form Factory
     */
    public FactoryUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tipoItems = new javax.swing.ButtonGroup();
        infoPanel = new javax.swing.JPanel();
        qtdeField = new javax.swing.JTextField();
        descricaoField = new javax.swing.JTextField();
        valorField = new javax.swing.JTextField();
        servicoButton = new javax.swing.JRadioButton();
        produtoButton = new javax.swing.JRadioButton();
        addItemButton = new javax.swing.JButton();
        tipoLabel = new javax.swing.JLabel();
        qtdeLabel = new javax.swing.JLabel();
        descricaoLabel = new javax.swing.JLabel();
        valorLabel = new javax.swing.JLabel();
        infoTitleLabel = new javax.swing.JLabel();
        produtosScrollPanel = new javax.swing.JScrollPane();
        produtosList = new javax.swing.JList<>();
        servicosScrollPanel = new javax.swing.JScrollPane();
        servicosList = new javax.swing.JList<>();
        editaProdButton = new javax.swing.JButton();
        excluiProdButton = new javax.swing.JButton();
        editaServButton = new javax.swing.JButton();
        excluiServButton = new javax.swing.JButton();
        exportaButton = new javax.swing.JButton();
        voltarButton = new javax.swing.JButton();
        totalProdLabel = new javax.swing.JLabel();
        precoProdLabel = new javax.swing.JLabel();
        totalServLabel = new javax.swing.JLabel();
        precoServLabel = new javax.swing.JLabel();
        totalLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tipoItems.add(servicoButton);
        servicoButton.setText("Serviço");
        servicoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                servicoButtonActionPerformed(evt);
            }
        });

        tipoItems.add(produtoButton);
        produtoButton.setText("Produto");

        addItemButton.setText("Adiciona Item");
        addItemButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addItemButtonActionPerformed(evt);
            }
        });

        tipoLabel.setText("Tipo:");

        qtdeLabel.setText("Quantidade:");

        descricaoLabel.setText("Descrição:");

        valorLabel.setText("Valor Unitário:");

        infoTitleLabel.setText("Informações do Item");

        javax.swing.GroupLayout infoPanelLayout = new javax.swing.GroupLayout(infoPanel);
        infoPanel.setLayout(infoPanelLayout);
        infoPanelLayout.setHorizontalGroup(
            infoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(infoPanelLayout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addGroup(infoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tipoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addItemButton)
                    .addComponent(produtoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(servicoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(descricaoLabel)
                    .addComponent(valorLabel)
                    .addComponent(infoTitleLabel)
                    .addComponent(descricaoField, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(infoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(qtdeField, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(qtdeLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(valorField, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(50, Short.MAX_VALUE))
        );
        infoPanelLayout.setVerticalGroup(
            infoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, infoPanelLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(infoTitleLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(qtdeLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(qtdeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(descricaoLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(descricaoField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(valorLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(valorField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(tipoLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(servicoButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(produtoButton)
                .addGap(18, 18, 18)
                .addComponent(addItemButton)
                .addGap(35, 35, 35))
        );

        produtosList.setBorder(javax.swing.BorderFactory.createTitledBorder("Produtos Listados"));
        produtosList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Qtde |-| Descrição |-| Valor UN |-| Sub-Total" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        produtosList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        produtosScrollPanel.setViewportView(produtosList);

        servicosList.setBorder(javax.swing.BorderFactory.createTitledBorder("Serviços Listados"));
        servicosList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Qtde |-| Descrição |-| Valor UN |-| Sub-Total" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        servicosList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        servicosScrollPanel.setViewportView(servicosList);

        editaProdButton.setText("Edita Produto");
        editaProdButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editaProdButtonActionPerformed(evt);
            }
        });

        excluiProdButton.setText("Exclui Produto");
        excluiProdButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                excluiProdButtonActionPerformed(evt);
            }
        });

        editaServButton.setText("Edita Serviço");
        editaServButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editaServButtonActionPerformed(evt);
            }
        });

        excluiServButton.setText("Exclui Serviço");
        excluiServButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                excluiServButtonActionPerformed(evt);
            }
        });

        exportaButton.setText("Exportar OS");
        exportaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exportaButtonActionPerformed(evt);
            }
        });

        voltarButton.setText("Voltar/Editar");
        voltarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voltarButtonActionPerformed(evt);
            }
        });

        totalProdLabel.setText("Total Serviços:");

        precoProdLabel.setText("R$ 00,00");

        totalServLabel.setText("Total Produtos:");

        precoServLabel.setText("R$ 00,00");

        totalLabel.setText("Total: R$ 0,00");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(infoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(totalLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(voltarButton))
                    .addComponent(servicosScrollPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(produtosScrollPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(exportaButton)
                    .addComponent(excluiServButton)
                    .addComponent(editaServButton)
                    .addComponent(precoServLabel)
                    .addComponent(totalProdLabel)
                    .addComponent(excluiProdButton)
                    .addComponent(editaProdButton)
                    .addComponent(precoProdLabel)
                    .addComponent(totalServLabel))
                .addContainerGap(65, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {editaProdButton, editaServButton, excluiProdButton, excluiServButton, exportaButton, voltarButton});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(infoPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(produtosScrollPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(totalServLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(precoProdLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(editaProdButton)
                        .addGap(18, 18, 18)
                        .addComponent(excluiProdButton)))
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(totalProdLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(precoServLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(editaServButton)
                        .addGap(18, 18, 18)
                        .addComponent(excluiServButton))
                    .addComponent(servicosScrollPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(totalLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(exportaButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(voltarButton))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addItemButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addItemButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addItemButtonActionPerformed

    private void servicoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_servicoButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_servicoButtonActionPerformed

    private void editaProdButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editaProdButtonActionPerformed
        // TODO add your handling code here:
        if(temProdSelecionado()){
            
            produtosList.remove(produtosList.getSelectedIndex());
        }
    }//GEN-LAST:event_editaProdButtonActionPerformed

    private void editaServButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editaServButtonActionPerformed
        // TODO add your handling code here:
        if(temSerSelecionado()){
            
            servicosList.remove(servicosList.getSelectedIndex());
        }
    }//GEN-LAST:event_editaServButtonActionPerformed

    private void exportaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exportaButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_exportaButtonActionPerformed

    private void voltarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voltarButtonActionPerformed
        // TODO add your handling code here:
        OS_Generator.factory.setVisible(false);
        OS_Generator.clientData.setVisible(true);
    }//GEN-LAST:event_voltarButtonActionPerformed

    private void excluiProdButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_excluiProdButtonActionPerformed
        // TODO add your handling code here:
        if(temProdSelecionado()){
            produtosList.remove(produtosList.getSelectedIndex());
        }
    }//GEN-LAST:event_excluiProdButtonActionPerformed

    private void excluiServButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_excluiServButtonActionPerformed
        // TODO add your handling code here:
        if(temSerSelecionado()){
            servicosList.remove(servicosList.getSelectedIndex());
        }
    }//GEN-LAST:event_excluiServButtonActionPerformed
    
    public boolean temProdSelecionado(){
        if(!produtosList.isSelectionEmpty()){
           if(produtosList.getSelectedIndex() != 0){
               return true;
           } 
        }
        return false;
    }
    
    public boolean temSerSelecionado(){
        if(!servicosList.isSelectionEmpty()){
           if(servicosList.getSelectedIndex() != 0){
               return true;
           } 
        }
        return false;
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FactoryUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FactoryUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FactoryUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FactoryUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FactoryUI().setVisible(false);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addItemButton;
    private javax.swing.JTextField descricaoField;
    private javax.swing.JLabel descricaoLabel;
    private javax.swing.JButton editaProdButton;
    private javax.swing.JButton editaServButton;
    private javax.swing.JButton excluiProdButton;
    private javax.swing.JButton excluiServButton;
    private javax.swing.JButton exportaButton;
    private javax.swing.JPanel infoPanel;
    private javax.swing.JLabel infoTitleLabel;
    private javax.swing.JLabel precoProdLabel;
    private javax.swing.JLabel precoServLabel;
    private javax.swing.JRadioButton produtoButton;
    private javax.swing.JList<String> produtosList;
    private javax.swing.JScrollPane produtosScrollPanel;
    private javax.swing.JTextField qtdeField;
    private javax.swing.JLabel qtdeLabel;
    private javax.swing.JRadioButton servicoButton;
    private javax.swing.JList<String> servicosList;
    private javax.swing.JScrollPane servicosScrollPanel;
    private javax.swing.ButtonGroup tipoItems;
    private javax.swing.JLabel tipoLabel;
    private javax.swing.JLabel totalLabel;
    private javax.swing.JLabel totalProdLabel;
    private javax.swing.JLabel totalServLabel;
    private javax.swing.JTextField valorField;
    private javax.swing.JLabel valorLabel;
    private javax.swing.JButton voltarButton;
    // End of variables declaration//GEN-END:variables
}
