/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui;
import java.awt.Color;
import os_generator.OS_Generator;
/**
 *
 * @author gabif
 */
public class MenuUI extends javax.swing.JFrame {
    
    /**
     * Creates new form Menu
     */
    public MenuUI() {
        initComponents();
    }
    
    public void setCoresUI(Color background, Color labels, Color button,
            Color buttonLabel){
        
        this.getContentPane().setBackground(background);
        this.titleLabel.setForeground(labels);
        
        this.editOrgDataButton.setBackground(button);
        this.editOrgDataButton.setForeground(buttonLabel);
        this.newOsButton.setBackground(button);
        this.newOsButton.setForeground(buttonLabel);
        this.configButton.setBackground(button);
        this.configButton.setForeground(buttonLabel);
    }
    
    public void habilitaNewOSButton(){
        OS_Generator.menu.newOsButton.setEnabled(true);
    }
    
    public void desabilitaNewOSButton(){
        OS_Generator.menu.newOsButton.setEnabled(false);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        newOsButton = new javax.swing.JButton();
        titleLabel = new javax.swing.JLabel();
        LogoPanel = new javax.swing.JPanel();
        editOrgDataButton = new javax.swing.JButton();
        configButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(300, 350));

        newOsButton.setText("Criar O.S.");
        newOsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newOsButtonActionPerformed(evt);
            }
        });

        titleLabel.setText("Gerenciador de Ordens de Serviço (O.S.)");

        javax.swing.GroupLayout LogoPanelLayout = new javax.swing.GroupLayout(LogoPanel);
        LogoPanel.setLayout(LogoPanelLayout);
        LogoPanelLayout.setHorizontalGroup(
            LogoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        LogoPanelLayout.setVerticalGroup(
            LogoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        editOrgDataButton.setText("Editar Dados da Empresa");
        editOrgDataButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editOrgDataButtonActionPerformed(evt);
            }
        });

        configButton.setText("Configurações");
        configButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                configButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(newOsButton)
                    .addComponent(titleLabel)
                    .addComponent(LogoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(editOrgDataButton)
                    .addComponent(configButton))
                .addContainerGap(48, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {configButton, editOrgDataButton, newOsButton});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(LogoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(titleLabel)
                .addGap(34, 34, 34)
                .addComponent(editOrgDataButton)
                .addGap(18, 18, 18)
                .addComponent(newOsButton)
                .addGap(18, 18, 18)
                .addComponent(configButton)
                .addGap(43, 43, 43))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void newOsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newOsButtonActionPerformed
        // TODO add your handling code here:
        OS_Generator.menu.setVisible(false);
        OS_Generator.clientData.setVisible(true);
        OS_Generator.clientData.resetaCampos();
    }//GEN-LAST:event_newOsButtonActionPerformed

    private void editOrgDataButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editOrgDataButtonActionPerformed
        // TODO add your handling code here:
        OS_Generator.menu.setVisible(false);
        OS_Generator.orgData.setVisible(true);
    }//GEN-LAST:event_editOrgDataButtonActionPerformed

    private void configButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_configButtonActionPerformed
        // TODO add your handling code here:
        OS_Generator.menu.setVisible(false);
        OS_Generator.configUi.setVisible(true);
    }//GEN-LAST:event_configButtonActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new MenuUI().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel LogoPanel;
    private javax.swing.JButton configButton;
    private javax.swing.JButton editOrgDataButton;
    private javax.swing.JButton newOsButton;
    private javax.swing.JLabel titleLabel;
    // End of variables declaration//GEN-END:variables
}
